import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import {
  ageInDays,
  cancelTask,
  closeTask,
  createTask,
  getMainPage,
  msUntilLocalMidnight,
  PRIORITY_LABELS,
  reopenTask,
  signOut,
  type TaskContext,
  type TaskView,
} from './api'
import TaskDetail from './TaskDetail'

type Filter = 'ALL' | 'WORK' | 'PERSONAL'

export default function MainPage() {
  const qc = useQueryClient()
  const [filter, setFilter] = useState<Filter>('ALL')
  const [error, setError] = useState<string | null>(null)
  const [showClosed, setShowClosed] = useState(true)
  const [selected, setSelected] = useState<string | null>(null)

  const { data, isPending, error: loadError } = useQuery({
    queryKey: ['tasks'],
    queryFn: getMainPage,
  })

  const refresh = () => qc.invalidateQueries({ queryKey: ['tasks'] })

  // Roll the "closed today" list over at the server's midnight. Without this a
  // tab left open overnight keeps yesterday's completions on screen.
  useEffect(() => {
    if (!data?.timezone) return
    const timer = setTimeout(refresh, msUntilLocalMidnight(data.timezone))
    return () => clearTimeout(timer)
  }, [data?.timezone, data?.closedToday])

  // Written out rather than generated by a helper: a function that calls
  // useMutation is a hook, and hiding that behind a plain-looking name is how
  // someone later moves one call inside a condition and breaks hook order.
  const onDone = { onSuccess: () => { setError(null); refresh() },
                   onError: (e: Error) => setError(e.message) }

  const add = useMutation({ mutationFn: createTask, ...onDone })
  const close = useMutation({ mutationFn: closeTask, ...onDone })
  const cancel = useMutation({ mutationFn: cancelTask, ...onDone })
  const reopen = useMutation({ mutationFn: reopenTask, ...onDone })

  const open = data?.open ?? []
  const visible = useMemo(
    () => (filter === 'ALL' ? open : open.filter(t => t.context === filter)),
    [open, filter],
  )

  // Children nest under their parent. A task whose parent is closed is still
  // open and its parent is not in this list, so it is promoted to top level
  // rather than disappearing.
  const openIds = useMemo(() => new Set(visible.map(t => t.id)), [visible])
  const childrenOf = useMemo(() => {
    const map = new Map<string, TaskView[]>()
    for (const t of visible) {
      if (t.parentId && openIds.has(t.parentId)) {
        map.set(t.parentId, [...(map.get(t.parentId) ?? []), t])
      }
    }
    return map
  }, [visible, openIds])
  const roots = visible.filter(t => !t.parentId || !openIds.has(t.parentId))

  if (isPending) return <main className="page">Loading...</main>
  if (loadError) return <main className="page"><p className="error">{(loadError as Error).message}</p></main>

  const closed = data?.closedToday ?? []

  return (
    <main className="page">
      <header className="header">
        <h1>Tasks</h1>
        <nav className="header-links">
          <a className="link" href="#/review">Review</a>
          <a className="link" href="#/analytics">Analytics</a>
          <a className="link" href="#/history">History</a>
          <button className="link" onClick={signOut}>Sign out</button>
        </nav>
      </header>

      <QuickAdd onAdd={t => add.mutate(t)} busy={add.isPending} />

      {error && <p className="error" role="alert">{error}</p>}

      <nav className="filters">
        {(['ALL', 'WORK', 'PERSONAL'] as Filter[]).map(f => (
          <button
            key={f}
            className={filter === f ? 'chip chip-on' : 'chip'}
            onClick={() => setFilter(f)}
          >
            {f === 'ALL' ? 'All' : f === 'WORK' ? 'Work' : 'Personal'}
          </button>
        ))}
        <span className="count">{visible.length} open</span>
      </nav>

      {roots.length === 0 ? (
        <p className="empty">Nothing open. Add something above.</p>
      ) : (
        <ul className="tasks">
          {roots.map(task => (
            <li key={task.id}>
              <TaskRow
                task={task}
                onOpen={() => setSelected(task.id)}
                onClose={() => close.mutate(task.id)}
                onCancel={() => cancel.mutate(task.id)}
              />
              {childrenOf.get(task.id) && (
                <ul className="tasks children">
                  {childrenOf.get(task.id)!.map(child => (
                    <li key={child.id}>
                      <TaskRow
                        task={child}
                        onOpen={() => setSelected(child.id)}
                        onClose={() => close.mutate(child.id)}
                        onCancel={() => cancel.mutate(child.id)}
                      />
                    </li>
                  ))}
                </ul>
              )}
            </li>
          ))}
        </ul>
      )}

      {(data?.closedYesterday ?? 0) > 0 && (
        <p className="yesterday">
          <a href="#/history">Yesterday: {data!.closedYesterday} done</a>
        </p>
      )}

      {closed.length > 0 && (
        <section className="closed">
          <button className="closed-toggle" onClick={() => setShowClosed(v => !v)}>
            {showClosed ? 'Hide' : 'Show'} closed today ({closed.length})
          </button>
          {showClosed && (
            <ul className="tasks">
              {closed.map(task => (
                <li key={task.id} className="done-row">
                  <button
                    className={task.status === 'CANCELLED' ? 'link done cancelled' : 'link done'}
                    onClick={() => setSelected(task.id)}
                  >
                    {task.title}
                  </button>
                  {task.status === 'CANCELLED' && <span className="badge">cancelled</span>}
                  <button className="link" onClick={() => reopen.mutate(task.id)}>Undo</button>
                </li>
              ))}
            </ul>
          )}
        </section>
      )}
      {selected && (
        <TaskDetail
          id={selected}
          onClose={() => setSelected(null)}
          onOpenOther={setSelected}
        />
      )}
    </main>
  )
}

function QuickAdd({ onAdd, busy }: { onAdd: (t: { title: string; priority: number; context: TaskContext }) => void; busy: boolean }) {
  const [title, setTitle] = useState('')
  const [priority, setPriority] = useState(2)
  const [context, setContext] = useState<TaskContext>('WORK')
  const input = useRef<HTMLInputElement>(null)

  // Press n to start typing. Capture takes two seconds or it stops happening.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement)?.tagName
      if (e.key === 'n' && tag !== 'INPUT' && tag !== 'TEXTAREA') {
        e.preventDefault()
        input.current?.focus()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  const submit = (e: FormEvent) => {
    e.preventDefault()
    const trimmed = title.trim()
    if (!trimmed) return
    onAdd({ title: trimmed, priority, context })
    setTitle('')
  }

  return (
    <form className="quickadd" onSubmit={submit}>
      <input
        ref={input}
        value={title}
        onChange={e => setTitle(e.target.value)}
        placeholder="What needs doing?  (press n)"
        aria-label="New task title"
        disabled={busy}
      />
      <select value={priority} onChange={e => setPriority(Number(e.target.value))} aria-label="Priority">
        {PRIORITY_LABELS.map((label, i) => <option key={label} value={i}>{label}</option>)}
      </select>
      <select value={context} onChange={e => setContext(e.target.value as TaskContext)} aria-label="Context">
        <option value="WORK">Work</option>
        <option value="PERSONAL">Personal</option>
      </select>
      <button type="submit" disabled={busy || !title.trim()}>Add</button>
    </form>
  )
}

function TaskRow({ task, onOpen, onClose, onCancel }: {
  task: TaskView
  onOpen: () => void
  onClose: () => void
  onCancel: () => void
}) {
  const age = ageInDays(task.createdAt)
  return (
    <div className="row">
      <button className="check" onClick={onClose} title="Mark done" aria-label={`Close ${task.title}`} />
      <span className={`pri pri-${task.priority}`}>{PRIORITY_LABELS[task.priority]}</span>
      {/* The title opens the detail panel; the circle closes the task. Making
          the whole row clickable would put those two a few pixels apart. */}
      <button className="title title-link" onClick={onOpen}>{task.title}</button>
      {task.childrenTotal > 0 && (
        <span className="progress">{task.childrenDone}/{task.childrenTotal} done</span>
      )}
      <span className={task.context === 'WORK' ? 'ctx ctx-work' : 'ctx ctx-personal'}>
        {task.context === 'WORK' ? 'work' : 'personal'}
      </span>
      {age > 0 && <span className="age">{age}d</span>}
      <button className="link subtle" onClick={onCancel} title="Cancel (did not do this)">cancel</button>
    </div>
  )
}
